import type { AnalyzeRequest, AnalyzeResponse } from "./types.ts";

type SampleScenario = {
  id: string;
  label: string;
  description: string;
  input: Required<AnalyzeRequest>;
  result: Pick<AnalyzeResponse, "max_safe_offer" | "net_profit" | "total_project_cost">;
};

// Fictional presets generated by the existing backend at efe27e0, not a second
// calculator. Browser CI checks every result against the real analysis API.
const assumptions = {
  purchase_price: 150000, arv: 270000,
  closing_cost_pct: 0.03, selling_cost_pct: 0.08,
  annual_interest_rate: 0.10, loan_to_cost_pct: 0.90,
  required_profit_margin_pct: 0.12, est_monthly_rent: null, region: null,
} as const;

export const SAMPLE_SCENARIOS = [
  {
    id: "estimate", label: "Original estimate",
    description: "$50,000 rehab. Six months to sell.",
    input: { ...assumptions, rehab_budget: 50000, holding_months: 6 },
    result: { max_safe_offer: 155600, net_profit: 34900, total_project_cost: 235100 },
  },
  {
    id: "quote", label: "A higher rehab quote",
    description: "$67,000 rehab. Same six-month schedule.",
    input: { ...assumptions, rehab_budget: 67000, holding_months: 6 },
    result: { max_safe_offer: 139000, net_profit: 17135, total_project_cost: 252865 },
  },
  {
    id: "delay", label: "The quote, plus a delay",
    description: "$67,000 rehab. Now eight months to sell.",
    input: { ...assumptions, rehab_budget: 67000, holding_months: 8 },
    result: { max_safe_offer: 136200, net_profit: 13880, total_project_cost: 256120 },
  },
] as const satisfies readonly SampleScenario[];
